FROM openjdk:8-jre
EXPOSE 8080

# JMeter version
ARG JMETER_VERSION=4.0

# Install few utilities
RUN apt-get clean && \
    apt-get update && \
    apt-get -qy install \
                wget \
                telnet \
                iputils-ping \
                unzip

# Install JMeter
RUN   mkdir /jmeter \
      && cd /jmeter/ \
      && wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
      && tar -xzf apache-jmeter-$JMETER_VERSION.tgz \
      && rm apache-jmeter-$JMETER_VERSION.tgz

# ADD all the plugins
#ADD F:/code/Hub/stressTestPlatform/jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar /jmeter/apache-jmeter-$JMETER_VERSION/lib/ext/jmeter-plugins-dubbo-2.7.3-jar-with-dependencies.jar

ADD jmeter.properties /jmeter/apache-jmeter-$JMETER_VERSION/bin/jmeter.properties

# Set JMeter Home
ENV JMETER_HOME /jmeter/apache-jmeter-$JMETER_VERSION/

# Add JMeter to the Path
ENV PATH $JMETER_HOME/bin:$PATH

VOLUME /tmp
ADD renren-fast.jar /app.jar

EXPOSE 1099 50000

RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-jar","/app.jar","--spring.profiles.active=pro"]
